
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'MUL NUM PLUSexpr : expr PLUS termexpr : termterm : term MUL NUMterm : NUM'
    
_lr_action_items = {'NUM':([0,4,5,],[3,3,7,]),'$end':([1,2,3,6,7,],[0,-2,-4,-1,-3,]),'PLUS':([1,2,3,6,7,],[4,-2,-4,-1,-3,]),'MUL':([2,3,6,7,],[5,-4,5,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,],[1,]),'term':([0,4,],[2,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS term','expr',3,'p_expr_plus','try.py',23),
  ('expr -> term','expr',1,'p_expr_term','try.py',27),
  ('term -> term MUL NUM','term',3,'p_term_mul','try.py',31),
  ('term -> NUM','term',1,'p_term_num','try.py',35),
]
